---
version: '3.5'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8282:80'
    environment:
      PMA_HOST: 64.225.87.71
      MYSQL_ROOT_PASSWORD: otgi$AsHmu7dTe 