---
- name: Install Utility software
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - software-properties-common

- name: Add apt key
  command: apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'

- name: Add MariaDB Repo
  apt_repository:
    filename: MariaDB-10.2
    repo: deb [arch=amd64,arm64,ppc64el] http://sgp1.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal main
    state: present

- name: "Installing python apt dependencies"
  apt:
    name: "{{item}}"
  with_items:
    - python3-pip
    - python3-dev 

- name: Install the MariaDB packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ ubuntu_mysql_pkgs }}"

- name: Update MariaDB root password for all root accounts 
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the templates to their respestive destination
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root 
    group: root 
    mode: "{{ item.mode | default(644) }}"
  with_items:
    - { src: 'my.cnf.j2', dest: '/etc/mysql/my.cnf' }
    - { src: 'root.cnf.j2', dest: '~/.my.cnf', mode: '600' }
  notify:
    - Restart MariaDB

- name: Ensure Anonymous user(s) are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
 
- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  notify:
    - Restart MariaDB 
